version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PUBLIC_PORT}:6379"
    volumes:
      - redis:/data
    networks:
      - nft-minting-services_net
    restart: always

#  mongo:
#    image: mongo:latest
#    ports:
#      - "${MONGO_PUBLIC_PORT}:27017"
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=mongo
#      - MONGO_INITDB_ROOT_PASSWORD=qweqwe123
#    volumes:
#      - mongo:/data/db
#    networks:
#      - nft-minting-services_net
#    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: booka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweqwe123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_PUBLIC_PORT}:5432"
    networks:
      - nft-minting-services_net
    restart: always

  node_worker:
    build: .
    depends_on:
      - postgres
    ports:
      - "${WORKER_PUBLIC_PORT}:3000"
    secrets:
      - source: environment-config
        target: /app/.env
        mode: 0444
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run start
    networks:
      - nft-minting-services_net
    restart: always

  node_worker-chain:
    build: .
    depends_on:
      - postgres
    ports:
      - "${WORKER_CHAIN_PUBLIC_PORT}:3001"
    secrets:
      - source: environment-config
        target: /app/.env
        mode: 0444
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run start-chain
    networks:
      - nft-minting-services_net
    restart: always

networks:
  nft-minting-services_net:

volumes:
  postgres:
  redis:

secrets:
  environment-config:
    file: ./.env-docker

