import { CardInfo } from '@koniverse/telegram-bot-grpc';
import { CardStat } from '@src/services/game/mythicalGame/MythicalCardGameService';

export const Card_Player_Default: CardInfo[] = [{
  defId: '1jelliott4ea1',
  firstName: 'Jake',
  lastName: 'Elliott',
  team: 'eagles',
  position: 'K',
  rarity: 'rare',
  isDefault: true,
  stars: 2,
  level: 1,
  power: 80,
  strength: 27,
  quickness: 42,
  acceleration: 60,
  presence: 26,
  endurance: 54,
  jump: 38,
  carry: 29,
  image: 'https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Jake_Elliott.png',
}, {
  defId: '1jferguson65cw1',
  firstName: 'Jake',
  lastName: 'Ferguson',
  team: 'cowboys',
  position: 'TE',
  rarity: 'common',
  isDefault: true,
  stars: 1,
  level: 1,
  power: 68,
  strength: 56,
  quickness: 61,
  acceleration: 52,
  presence: 65,
  endurance: 87,
  jump: 65,
  carry: 65,
  image: 'https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Jake_Ferguson.png',
}, {
  defId: '1qwilliams56je1',
  firstName: 'Quincy',
  lastName: 'Williams',
  team: 'jets',
  position: 'LB',
  rarity: 'common',
  isDefault: true,
  stars: 1,
  level: 1,
  power: 68,
  strength: 56,
  quickness: 65,
  acceleration: 75,
  presence: 49,
  endurance: 61,
  jump: 84,
  carry: 40,
  image: 'https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Quincy_Williams.png',
}, {
  defId: '1xmckinney29gi1',
  firstName: 'Xavier',
  lastName: 'McKinney',
  team: 'packers',
  position: 'FS',
  rarity: 'rare',
  isDefault: true,
  stars: 2,
  level: 1,
  power: 71,
  strength: 58,
  quickness: 84,
  acceleration: 75,
  presence: 57,
  endurance: 80,
  jump: 85,
  carry: 57,
  image: 'https://gs-assets.mythical.dev/AdminAssets/nflrivals/1/Xavier_McKinney.png',
}];


export const CardStatArr: CardStat[] = [
  CardStat.PRE,
  CardStat.END,
  CardStat.POW,
  CardStat.QUI,
  CardStat.JMP,
  CardStat.ACC,
  CardStat.STR,
  CardStat.CAR];